name : FunnY TexT Printer on a PR

on: 
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  print-Funny_Text:
    runs-on: ubuntu-latest

    steps:
      - name: node.js setup
        uses : actions/setup-node@v2
        with :
            node-version : '14'
            
      
     
      
    
    
    
      - name: FunnyText
        run: .github\workflows\FunnyText.js
