name : FunnY TexT Printer on a PR

on: 
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  print-Funny_Text:
    runs-on: ubuntu-latest

    steps:
      - name: FunnyText
        run: node /.github/workflows/FunnyText.js
